language: python
python:
  - "2.7"
install:
  - pip install flake8
  - pip install git+ssh://git@github.com/openlabs/trytond-product-code.git@develop
  - python setup.py install
script:
  - python setup.py test
  - flake8 .
