language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install flake8
  - python setup.py install
  - pip install git+ssh://git@github.com/openlabs/trytond-product-code.git@2.8.0.1
script:
  - python setup.py test
  - flake8 .
